name: build-and-deploy

on:
  workflow_call:
    secrets:
      PLANTON_CLOUD_CLIENT_ID:
        required: true
      PLANTON_CLOUD_CLIENT_SECRET:
        required: true
    inputs:
      PLANTON_CLOUD_ARTIFACT_STORE_ID:
        required: true
        type: string
      DOCKER_REPO_HOSTNAME:
        required: true
        type: string
      CONTAINER_IMAGE_REPO:
        required: true
        type: string
      CONTAINER_IMAGE_TAG:
        required: true
        type: string
      PLANTON_CLOUD_ENVIRONMENT_ID:
        required: true
        type: string
      PLANTON_CLOUD_ENVIRONMENT_NAME:
        required: true
        type: string
      PLANTON_CLOUD_MICROSERVICE_INSTANCE_VERSION:
        required: true
        type: string
      NODEJS_VERSION:
        required: false
        type: string
        default: 18.6
      YARN_VERSION:
        required: false
        type: string
        default: 3.6.1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.PLANTON_CLOUD_ENVIRONMENT_ID }}-${{ inputs.PLANTON_CLOUD_MICROSERVICE_INSTANCE_VERSION }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Install Planton CLI
        uses: plantoncloud/install-planton-cli-action@main
      
      - name: Login to Planton Cloud
        uses: plantoncloud/planton-cli-login-action@main
        with:
          planton_cloud_client_id: ${{ secrets.PLANTON_CLOUD_CLIENT_ID }}
          planton_cloud_client_secret: ${{ secrets.PLANTON_CLOUD_CLIENT_SECRET }}

      - name: Export Buf Token
        run: |
          BUF_TOKEN=$(planton get ${{ inputs.PLANTON_CLOUD_ARTIFACT_STORE_ID }} -oyaml | yq e '.spec.bufToken' -)
          echo "BUF_TOKEN=$BUF_TOKEN" >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.NODEJS_VERSION }}
          cache: 'yarn'

      # https://github.com/actions/setup-node/issues/325#issuecomment-1120962692
      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: Install Yarn V3
        run: |
          corepack enable
          corepack prepare yarn@${{ inputs.YARN_VERSION }} --activate
          yarn --version
        shell: bash

      - name: Build with Make
        run:  make build

      - name: GCP Artifact Registry Docker Login
        uses: plantoncloud/gcp-artifact-registry-docker-login-action@main
        with:
          planton_cloud_artifact_store_id: ${{ inputs.PLANTON_CLOUD_ARTIFACT_STORE_ID }}
          docker_repo_hostname: ${{ inputs.DOCKER_REPO_HOSTNAME }}

      - name: Build & Push Docker Image
        uses: plantoncloud/build-and-push-docker-image-action@main
        with:
          docker_repo_hostname: ${{ inputs.DOCKER_REPO_HOSTNAME }}
          container_image_repo: ${{ inputs.CONTAINER_IMAGE_REPO }}
          container_image_tag: ${{ inputs.CONTAINER_IMAGE_TAG }}

      - name: Deploy Microservice
        uses: plantoncloud/deploy-microservice-action@main
        with:
          planton_cloud_environment_name: ${{ inputs.PLANTON_CLOUD_ENVIRONMENT_NAME }}
          planton_cloud_microservice_instance_version: ${{ inputs.PLANTON_CLOUD_MICROSERVICE_INSTANCE_VERSION }}
          container_image_tag: ${{ inputs.CONTAINER_IMAGE_TAG }}
